apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: <APP_NAME>-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: <EKS_CLUSTER_NAME>
            namespace: <K8S_NAMESPACE>
  template:
    metadata:
      name: <APP_NAME>-{{cluster}}
    spec:
      project: <ARGOCD_PROJECT>
      source:
        repoURL: <GITOPS_REPOSITORY>
        targetRevision: <GITOPS_BRANCH>
        path: environments/{{cluster}}/<APP_NAME>
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

