replicaCount: 2

image:
  repository: <ECR_REPOSITORY>
  tag: <IMAGE_TAG>
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

ingress:
  enabled: false
  host: <APP_HOSTNAME>

